// Guild agent orchestration — triggers real Guild sessions for each of the
// five Phalanx agents (scanner, analyst, planner, validator, operator).
//
// Transport: shells out to the `guild agent chat --mode json` CLI with each
// agent's local path. The CLI streams an LLM session against the published
// agent version (or the local unsaved copy when `--ephemeral` is passed).
// Response JSON is parsed through a zod schema at the boundary; orchestrator
// code only ever handles validated, typed output.
//
// Every exported function takes `scanId: string` as the FIRST argument and
// emits:
//   - `guild.action`           per successful agent turn (audit log)
//   - `guild.approval.granted` when the operator returns APPROVE
//   - `guild.approval.denied`  when the operator returns REJECT or HOLD
//
// The AGENT_PATHS resolver looks under $PHALANX_AGENTS_DIR or the default
// "../agents" (relative to the Next.js project root). In production this
// would swap to the Guild HTTP API directly once a stable Node SDK ships.

import { execFile, spawn } from 'node:child_process';
import { promisify } from 'node:util';
import { createHash, randomUUID } from 'node:crypto';
import * as path from 'node:path';
import * as fs from 'node:fs';
import { emitEvent } from '@/lib/events/emitter';
import {
    AGENT_NAMES,
    scannerOutputSchema,
    analystOutputSchema,
    plannerOutputSchema,
    validatorOutputSchema,
    operatorOutputSchema,
    type PhalanxAgentName,
    type ScannerOutput,
    type AnalystOutput,
    type PlannerOutput,
    type ValidatorOutput,
    type OperatorOutput,
    type ScannerFinding,
    type ValidationResult,
    type EvidenceBundle,
    type GuildActionEvent,
} from './types';

const execFileAsync = promisify(execFile);

const DEFAULT_AGENTS_DIR = path.resolve(process.cwd(), '..', 'agents');
const AGENTS_DIR = process.env.PHALANX_AGENTS_DIR ?? DEFAULT_AGENTS_DIR;

const GUILD_CLI_TIMEOUT_MS = Number(
    process.env.PHALANX_GUILD_TIMEOUT_MS ?? 120_000,
);

// Agent ID → agent name mapping for quick reverse lookups. The IDs come from
// each agent's guild.json (generated by `guild agent init`, gitignored). We
// read them lazily; in production this table would be pinned in env config.
interface AgentMeta {
    name: PhalanxAgentName;
    path: string;
    agentId: string | null;
}

function loadAgentMeta(name: PhalanxAgentName): AgentMeta {
    const agentPath = path.join(AGENTS_DIR, name);
    let agentId: string | null = null;
    const guildJson = path.join(agentPath, 'guild.json');
    try {
        const raw = fs.readFileSync(guildJson, 'utf8');
        const parsed = JSON.parse(raw) as { agent_id?: string };
        agentId = parsed.agent_id ?? null;
    } catch {
        // No guild.json — agent not initialized on this host. That's a real
        // configuration problem; surface it loudly rather than silently falling
        // back to a synthetic session.
    }
    return { name, path: agentPath, agentId };
}

function hashShort(payload: unknown): string {
    const s = typeof payload === 'string' ? payload : JSON.stringify(payload);
    return createHash('sha256').update(s).digest('hex').slice(0, 12);
}

interface ChatResult {
    sessionId: string;
    text: string;
    durationMs: number;
}

async function chat(
    name: PhalanxAgentName,
    prompt: string,
): Promise<ChatResult> {
    const meta = loadAgentMeta(name);
    if (!fs.existsSync(meta.path)) {
        throw new Error(
            `Guild agent "${name}" not installed at ${meta.path}. ` +
                `Run \`guild agent clone elijah-21296/${name}\` inside ${AGENTS_DIR} ` +
                `or set PHALANX_AGENTS_DIR.`,
        );
    }

    const sessionId = randomUUID();
    const startedAt = Date.now();
    const result = await new Promise<{ stdout: string; stderr: string }>((resolve, reject) => {
        const proc = spawn(
            'guild',
            ['agent', 'chat', '--path', meta.path, '--mode', 'json', '--no-splash', '--ephemeral'],
            { stdio: ['pipe', 'pipe', 'pipe'] },
        );
        let stdout = '';
        let stderr = '';
        const timer = setTimeout(() => { proc.kill(); reject(new Error('Guild agent timed out')); }, GUILD_CLI_TIMEOUT_MS);
        proc.stdout.on('data', (d: Buffer) => { stdout += d.toString(); });
        proc.stderr.on('data', (d: Buffer) => { stderr += d.toString(); });
        proc.on('close', (code: number) => {
            clearTimeout(timer);
            if (code === 0) resolve({ stdout, stderr });
            else reject(new Error(`guild agent chat exited ${code}\n  stderr: '${stderr}'`));
        });
        proc.on('error', (err: Error) => { clearTimeout(timer); reject(err); });
        const jsonInput = JSON.stringify({ prompt });
        proc.stdin.write(jsonInput + '\n');
        proc.stdin.end();
    });
    const durationMs = Date.now() - startedAt;
    return { sessionId, text: result.stdout, durationMs };
}

function extractJson(text: string): unknown {
    // Agents instructed to return strict JSON with no code fences. Be
    // defensive though — the CLI wraps the reply in a JSON-mode envelope we
    // need to peel. Accept any of:
    //   (a) a valid JSON document
    //   (b) an envelope like {"type":"text","text":"<json>"}
    //   (c) {"result":{"type":"text","text":"..."}}
    //   (d) fenced ```json block
    const trimmed = text.trim();
    if (!trimmed) return {};

    const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
    const candidate = fenced ? fenced[1] : trimmed;

    try {
        const parsed = JSON.parse(candidate);
        const unwrapped = unwrapEnvelope(parsed);
        return unwrapped;
    } catch {
        // Last-ditch: find the first `{` … matching `}` block.
        const start = candidate.indexOf('{');
        const end = candidate.lastIndexOf('}');
        if (start >= 0 && end > start) {
            try {
                return JSON.parse(candidate.slice(start, end + 1));
            } catch {
                return {};
            }
        }
        return {};
    }
}

function unwrapEnvelope(value: unknown): unknown {
    if (!value || typeof value !== 'object') return value;
    const v = value as Record<string, unknown>;
    if ('result' in v && typeof v.result === 'object' && v.result !== null) {
        return unwrapEnvelope(v.result);
    }
    if (v.type === 'text' && typeof v.text === 'string') {
        try {
            return JSON.parse(v.text);
        } catch {
            return { rawText: v.text };
        }
    }
    return value;
}

async function emitAction(
    scanId: string,
    ev: GuildActionEvent & { status?: 'ok' | 'error'; error?: string | null },
): Promise<void> {
    await emitEvent(scanId, {
        type: 'guild.action',
        source: 'guild',
        data: {
            ...ev,
            status: ev.status ?? 'ok',
        } as unknown as Record<string, unknown>,
    });
}

// ────────────────────────────────────────────────────────────────────────────
// Phase 0 — Scanner
// ────────────────────────────────────────────────────────────────────────────

export async function runScanner(
    scanId: string,
    repoUrl: string,
    manifest: string,
    options: { ecosystemHint?: string } = {},
): Promise<ScannerOutput> {
    const prompt = [
        `Repository: ${repoUrl}`,
        options.ecosystemHint ? `Ecosystem hint: ${options.ecosystemHint}` : null,
        '',
        'Dependency manifest follows:',
        manifest,
    ]
        .filter((line): line is string => line !== null)
        .join('\n');

    const meta = loadAgentMeta('phalanx-scanner');
    const { sessionId, text, durationMs } = await chat('phalanx-scanner', prompt);
    const output = scannerOutputSchema.parse(extractJson(text));

    await emitAction(scanId, {
        agentName: 'phalanx-scanner',
        agentId: meta.agentId ?? 'unknown',
        sessionId,
        action: 'scan.manifest',
        inputHash: hashShort({ repoUrl, manifest }),
        outputHash: hashShort(output),
        durationMs,
    });

    return output;
}

// ────────────────────────────────────────────────────────────────────────────
// Phase 2 — Analyst
// ────────────────────────────────────────────────────────────────────────────

export async function runAnalyst(
    scanId: string,
    finding: ScannerFinding,
    repoUrl: string,
    options: { depthHint?: number; callGraphHint?: string } = {},
): Promise<AnalystOutput> {
    const prompt = [
        `Scanner finding:`,
        JSON.stringify(finding, null, 2),
        '',
        `Repository: ${repoUrl}`,
        options.depthHint ? `Max transitive depth: ${options.depthHint}` : null,
        options.callGraphHint ? `Call-graph hint: ${options.callGraphHint}` : null,
    ]
        .filter((line): line is string => line !== null)
        .join('\n');

    const meta = loadAgentMeta('phalanx-analyst');
    const { sessionId, text, durationMs } = await chat('phalanx-analyst', prompt);
    const output = analystOutputSchema.parse(extractJson(text));

    await emitAction(scanId, {
        agentName: 'phalanx-analyst',
        agentId: meta.agentId ?? 'unknown',
        sessionId,
        action: 'analyst.verdict',
        inputHash: hashShort({ finding, repoUrl }),
        outputHash: hashShort(output),
        durationMs,
    });

    if (output.recommendCancel && output.confidence >= 0.9) {
        await emitEvent(scanId, {
            type: 'guild.cancel.broadcast',
            source: 'guild',
            data: {
                cveId: output.cveId,
                reason: 'false_positive',
                confidence: output.confidence,
                sourceAgent: 'phalanx-analyst',
            },
        });
    }

    return output;
}

// ────────────────────────────────────────────────────────────────────────────
// Phase 3 — Planner
// ────────────────────────────────────────────────────────────────────────────

export async function runPlanner(
    scanId: string,
    analyst: AnalystOutput,
    finding: ScannerFinding,
    options: { hypothesisCount?: number } = {},
): Promise<PlannerOutput> {
    const prompt = [
        'Analyst verdict:',
        JSON.stringify(analyst, null, 2),
        '',
        'Scanner finding:',
        JSON.stringify(finding, null, 2),
        '',
        `N=${options.hypothesisCount ?? 4}`,
    ].join('\n');

    const meta = loadAgentMeta('phalanx-planner');
    const { sessionId, text, durationMs } = await chat('phalanx-planner', prompt);
    const output = plannerOutputSchema.parse(extractJson(text));

    await emitAction(scanId, {
        agentName: 'phalanx-planner',
        agentId: meta.agentId ?? 'unknown',
        sessionId,
        action: 'planner.hypotheses',
        inputHash: hashShort({ analyst, finding }),
        outputHash: hashShort(output),
        durationMs,
    });

    return output;
}

// ────────────────────────────────────────────────────────────────────────────
// Phase 5 — Validator
// ────────────────────────────────────────────────────────────────────────────

export async function runValidator(
    scanId: string,
    planner: PlannerOutput,
    results: ValidationResult[],
): Promise<ValidatorOutput> {
    const prompt = [
        'Planner hypotheses:',
        JSON.stringify(planner, null, 2),
        '',
        'Validation results (per hypothesis):',
        JSON.stringify(results, null, 2),
        '',
        `Repository: ${planner.repoUrl}`,
        `CVE: ${planner.cveId}`,
    ].join('\n');

    const meta = loadAgentMeta('phalanx-validator');
    const { sessionId, text, durationMs } = await chat('phalanx-validator', prompt);
    const output = validatorOutputSchema.parse(extractJson(text));

    await emitAction(scanId, {
        agentName: 'phalanx-validator',
        agentId: meta.agentId ?? 'unknown',
        sessionId,
        action: 'validator.rank',
        inputHash: hashShort({ planner, results }),
        outputHash: hashShort(output),
        durationMs,
    });

    return output;
}

// ────────────────────────────────────────────────────────────────────────────
// Phase 5/6 — Operator (multi-turn approval gate)
// ────────────────────────────────────────────────────────────────────────────

export interface ApprovalOptions {
    /** Pre-recorded human decision — used for automated demos where the
     *  approval is granted non-interactively. If omitted, the Guild CLI
     *  prompts interactively. */
    autoDecision?: 'APPROVE' | 'REJECT' | 'HOLD';
    autoApprover?: string;
    autoReason?: string;
}

export async function runApprovalGate(
    scanId: string,
    validator: ValidatorOutput,
    evidence: EvidenceBundle,
    options: ApprovalOptions = {},
): Promise<OperatorOutput> {
    const meta = loadAgentMeta('phalanx-operator');
    if (!validator.winner) {
        throw new Error(
            'runApprovalGate: validator returned no winner — cannot request approval',
        );
    }

    const prompt = [
        'Validator output:',
        JSON.stringify(validator, null, 2),
        '',
        'Evidence bundle:',
        JSON.stringify(evidence, null, 2),
        '',
        options.autoDecision
            ? `Pre-approved decision: ${options.autoDecision} by ${options.autoApprover ?? 'operator-human'} (reason: ${options.autoReason ?? 'demo'})`
            : 'Present the approval prompt to the human now.',
    ].join('\n');

    const { sessionId, text, durationMs } = await chat('phalanx-operator', prompt);
    const output = operatorOutputSchema.parse(extractJson(text));

    await emitAction(scanId, {
        agentName: 'phalanx-operator',
        agentId: meta.agentId ?? 'unknown',
        sessionId,
        action: `operator.${output.decision.toLowerCase()}`,
        inputHash: hashShort({ validator, evidence }),
        outputHash: hashShort(output),
        durationMs,
    });

    const gateId = `prod-deploy-gate-${validator.cveId}`;
    if (output.decision === 'APPROVE') {
        await emitEvent(scanId, {
            type: 'guild.approval.granted',
            source: 'guild',
            data: {
                gateId,
                approver: output.approver,
                decisionReason: output.reason,
                hypothesisId: output.hypothesisId,
                actions: output.actions,
                productionTouched: output.productionTouched,
            },
        });
    } else {
        await emitEvent(scanId, {
            type: 'guild.approval.denied',
            source: 'guild',
            data: {
                gateId,
                approver: output.approver,
                decision: output.decision,
                reason: output.reason,
                hypothesisId: output.hypothesisId,
                followup: output.followup,
            },
        });
    }

    return output;
}

// ────────────────────────────────────────────────────────────────────────────
// Utilities
// ────────────────────────────────────────────────────────────────────────────

export function listPhalanxAgents(): { name: PhalanxAgentName; agentId: string | null }[] {
    return AGENT_NAMES.map((name) => {
        const meta = loadAgentMeta(name);
        return { name, agentId: meta.agentId };
    });
}
